scoreboard:
  title: "&b&lProxima Network"
  lines:
    - "&7&m-----------------------"
    - "&bRank&7:"
    - "&7%rank%"
    - ""
    - "&bOnline&7:"
    - "&f%playerCount%"
    - ""
    - "&3&osolardev.xyz"
    - "&7&m-----------------------"
